name: Benchmark test

on: [push, pull_request]

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Worker info
      run: |
        cat /proc/cpuinfo
        cat /proc/meminfo      
    - run: npm run bench common
      env:
        CI: true
