name: CI test

on: [push, pull_request]

jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Start transporter/cacher dependencies
      run: docker-compose up -d
      working-directory: ./test

    - name: Sleeping 30 secs
      run: sleep 30

    - name: Check containers
      run: docker-compose ps
      working-directory: ./ci-test

    - name: Check logs
      run: docker-compose logs
      working-directory: ./ci-test

    - name: Execute unit tests
      run: npm run test

    - name: Execute transporter tests
      run: npm run test:trans

    - name: Execute AMQP tests
      run: npm run test:amqp

    - name: Execute NATS tests
      run: npm run test:nats

    - name: Execute Typescript tests
      run: npm run test:ts

    - name: Upload code coverage
      run: npm run coverall

    - name: Stop containers
      run: npm run dc:down
      working-directory: ./ci-test
